# Generated by Django 5.2.13 on 2026-05-30 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        ('publications', '0004_alter_publicationcontributor_publication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='publications.publication'),
        ),
    ]
