# Generated by Django 5.2.13 on 2026-05-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_alter_publication_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='delete_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
