# Generated by Django 5.2.13 on 2026-05-30 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_alter_publication_delete_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationcontributor',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='publications.publication'),
        ),
        migrations.AlterField(
            model_name='publicationinvitation',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='publications.publication'),
        ),
    ]
